name: Tag Current Commit

on:
  push:
    branches:
      - add-multi-lock-unlock  # Change this to your default branch if different

jobs:
  tag-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      id: setup_python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Create Tag
      run: |
        TAG_NAME=`python setup.py --version`

        git tag $TAG_NAME
        git push origin $TAG_NAME